source 'https://rubygems.org'

ruby '2.1.3'
gem 'rails', '~> 4.1.4'

# FRONT END

# Use SCSS for stylesheets.
gem 'sass-rails', '~> 4.0.3'

# Compass tools for use with SCSS.
gem 'compass-rails', '~> 2.0.0'

# Font-awesome icons.
gem 'font-awesome-rails'

# Bootstrap.
gem 'bootstrap-sass', '~> 3.2.0'

# Use Uglifier as compressor for JavaScript assets.
gem 'uglifier'

# For enabling requirejs-style AMD scripts in the asset pipeline.
gem 'requirejs-rails', '~> 0.9.2'

# For HAML HTML view templates.
gem 'haml-rails', '~> 0.5.3'

# SERVER

gem 'unicorn'

# App config and ENV variables for heroku.
gem 'figaro', '~> 1.0.0'

group :production, :staging do
  # Enables serving assets in production and setting logger to standard out.
  gem 'rails_12factor'
end

# dev and debugging tools
group :development do
  gem 'quiet_assets', '~> 1.0.3'
  gem 'better_errors', '~> 2.0.0'
  gem 'binding_of_caller', '~> 0.7.2', platforms: [:mri_19, :rbx]

  # For linting JS with `rake jshint`.
  gem 'jshintrb'

  # For code documentation, run `yard --help` for list of commands.
  gem 'yard'
end
