# First, copy this file to a new one called "application.yml" in the same
# config directory.

# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development.
# Read more about figaro here: https://github.com/laserlemon/figaro

# Note that changes to this file will require a server restart to take effect.

DOMAIN_NAME: lvh.me

# If you have a Google Analytics account you want to use to track visits
# to this app, set your ID and domain name below.
# An example ID is 'UA-40905632-1', and an example domain is 'smc-connect.org'.
# Note that you must have a Universal Analytics property for tracking to work.
# https://support.google.com/analytics/answer/4457764?hl=en
# GOOGLE_ANALYTICS_ID:
# GOOGLE_ANALYTICS_DOMAIN:
